# Generated by Django 5.2 on 2025-04-24 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0004_alter_ads_created_at_alter_review_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ads",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
            },
        ),
    ]
